### PR TITLE
Add health endpoint

### PR DESCRIPTION
**Pull request by sebastien-comeau**
### Description

List of proposed changes:

- Add health endpoint

### What to test for/How to test

Load the application and hit `/api/health`

### CODE REVIEW

**Comment by gregory-j-baker** [comment]
Would you mind adding a sample response payload so we can see what this endpoint outputs?

**Comment by sebastien-comeau** [comment]
> Would you mind adding a sample response payload so we can see what this endpoint outputs?

In the PR or the Readme file?

**Review by gregory-j-baker — APPROVED** [review]

**Comment by gregory-j-baker** [comment]
> In the PR or the Readme file?

Nevermind.. I kinda jumped the gun; it's obvious what this will output.

**Comment by sebastien-comeau** [comment]
> > In the PR or the Readme file?
> 
> Nevermind.. I kinda jumped the gun; it's obvious what this will output.

For you own pleasure:

```json
{
  "appBaseUri": "http://localhost:3000/",
  "buildDate": "2023-01-12",
  "environment": "dev",
  "status": "UP",
  "uptime": "4.7485742 seconds"
}
```

**Pull request merged**
