### PR TITLE
Fix ternary operators should not be nested

### PR DESCRIPTION
**Pull request by sebastien-comeau**
### Description

List of proposed changes:

- Fix sonarlint warning : Fix ternary operators should not be nested

image

### What to test for/How to test

Status page should act like before.

### Additional Notes

Ternary operators should not be nested rule information
https://rules.sonarsource.com/javascript/RSPEC-3358

### CODE REVIEW

**Comment by s-laugh** [comment]
Well... I do disagree with this... 

Clean and easy reading of code requires a function to have a single input and a single output.
In addition, braking a if into multiple if statements doesn't help one bit, (i'd expect each if to execute, but the return inside a if prevents that from happening); it should be using if else so show a single flow of logic (if it wasn't for the fact that we are looking for undefined and null, a switch would be the better option).

**Comment by sebastien-comeau** [comment]
> Well... I do disagree with this...
> 
> Clean and easy reading of code requires a function to have a single input and a single output. In addition, braking a if into multiple if statements doesn't help one bit, (i'd expect each if to execute, but the return inside a if prevents that from happening); it should be using if else so show a single flow of logic (if it wasn't for the fact that we are looking for undefined and null, a switch would be the better option).
> 
> _I do understand that sometime readability can just be a preference thing; IMO this change does not help._

It's a kind of conditional rendering your will see often.

image

https://reactjs.org/docs/conditional-rendering.html

Or an element variable or inline If with logical && operator can be used.

**Comment by s-laugh** [comment]
> It's a kind of conditional rendering your will see often.

I know... it pains me. 

In general I give myself one exception to the single in/out rule when writting, that's to fail fast out of a function. 
So more like what we see here on the page (it could be a return if warranted, in this case throw is more direct at achieving the result we want) https://github.com/DTS-STN/passport-status/blob/6daaefe609c638fc97c52010e7f5f4b69ab77df5/pages/status.tsx#L94

I do agree that complex if conditions should not use the short operators `? : &&` as it becomes hard to read, instead should write out the long format if. But I wouldn't go out of my way to change what's already been put in place unless working on it directly.

If @Maxim-Lam and @krischarbonneau want this change, I won't object; it's just not my prefrence.

**Comment by Maxim-Lam** [comment]
> > It's a kind of conditional rendering your will see often.
> 
> I know... it pains me.
> 
> In general I give myself one exception to the single in/out rule when writting, that's to fail fast out of a function. So more like what we see here on the page (it could be a return if warranted, in this case throw is more direct at achieving the result we want)
> 
> https://github.com/DTS-STN/passport-status/blob/6daaefe609c638fc97c52010e7f5f4b69ab77df5/pages/status.tsx#L94
> 
> I do agree that complex if conditions should not use the short operators `? : &&` as it becomes hard to read, instead should write out the long format if. But I wouldn't go out of my way to change what's already been put in place unless working on it directly.
> 
> If @Maxim-Lam and @krischarbonneau want this change, I won't object; it's just not my prefrence.

I can see both sides of the argument being valid, If statements are just more easily readable at a glance and it's scope is much more visible. No objections either way

**Comment by krischarbonneau** [comment]
> > It's a kind of conditional rendering your will see often.
> 
> I know... it pains me.
> 
> In general I give myself one exception to the single in/out rule when writting, that's to fail fast out of a function. So more like what we see here on the page (it could be a return if warranted, in this case throw is more direct at achieving the result we want)
> 
> https://github.com/DTS-STN/passport-status/blob/6daaefe609c638fc97c52010e7f5f4b69ab77df5/pages/status.tsx#L94
> 
> I do agree that complex if conditions should not use the short operators `? : &&` as it becomes hard to read, instead should write out the long format if. But I wouldn't go out of my way to change what's already been put in place unless working on it directly.
> 
> If @Maxim-Lam and @krischarbonneau want this change, I won't object; it's just not my prefrence.

I think this is where I stand too. Generally I don't like nesting ternary operators since it reduces readability but in this case I don't think it was too complex. I'm okay with switching to the long form if conditions to improve readability and if for whatever reason we add more logic to this page it will help in the long run as well.

**Review by krischarbonneau — APPROVED** [review]
I'm okay with this if the others are.

**Pull request merged**
